services:
  my-blog-web:
    build: .
    container_name: my-blog-nextjs
    restart: unless-stopped
    ports:
      - "3005:3000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - NEXT_PUBLIC_APP_URL=${NEXT_PUBLIC_APP_URL}
      - AUTH_SECRET=${AUTH_SECRET}
      - ADMIN_EMAIL=${ADMIN_EMAIL}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
