services:
  my-blog-web:
    build: .
    container_name: my-blog-nextjs
    restart: unless-stopped
    ports:
      - "3005:3000"
    environment:
      - DATABASE_URL=postgresql://admin:SecretPassword123!@192.168.1.153:5432/mydatabase?schema=public
      - NEXT_PUBLIC_APP_URL=https://kadiryilmaz.online
