name: Trigger Portainer Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Portainer Webhook
        run: |
          echo "Triggering Portainer Webhook for Deployment..."
          curl -sS -X POST "${{ secrets.PORTAINER_WEBHOOK_URL }}"
          echo "Webhook triggered successfully!"
